### ISSUE TITLE
Fast Travel / Column view

### ISSUE THREAD

**Issue by Jemsterr** [mouseplace/mh-travel-tweaks#1]
If you add an instant travel button next to each name, that would be perfect.

The list is pretty long, do you think you could put a third tab on the map page that has no map, but the locations in something like 3 columns so there is less scrolling?
(And it would need to be one-click travel if it is done that way, much like the simple-travel links: https://www.mousehuntgame.com/travel.php?quick=1 )

**Comment by bradp** [comment]
Added in version 2.0.0!

Adds a column view, when clicking a location you navigate there and then it will put you on the camp page. 

You can also set the 'Simple Travel' as the default tab for the travel page as well.

Thanks!
